// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5jVAeIdXaCY6lXeEe9l9cZLXITVsIGQ',
    appId: '1:895055745889:web:3bdb9b3386f65b8157eb20',
    messagingSenderId: '895055745889',
    projectId: 'abayedir',
    authDomain: 'abayedir.firebaseapp.com',
    storageBucket: 'abayedir.firebasestorage.app',
    measurementId: 'G-R543NDLPL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWD1g1bUePmjdtgAnfPcmaRWpEhrgVT34',
    appId: '1:895055745889:android:ddf42d3e8217600557eb20',
    messagingSenderId: '895055745889',
    projectId: 'abayedir',
    storageBucket: 'abayedir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD58iFXPTXoxe1g6EFFepKcVfm24OiAW_8',
    appId: '1:895055745889:ios:2f4bcccbd7ccc85f57eb20',
    messagingSenderId: '895055745889',
    projectId: 'abayedir',
    storageBucket: 'abayedir.firebasestorage.app',
    iosBundleId: 'com.example.abayEqub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD58iFXPTXoxe1g6EFFepKcVfm24OiAW_8',
    appId: '1:895055745889:ios:2f4bcccbd7ccc85f57eb20',
    messagingSenderId: '895055745889',
    projectId: 'abayedir',
    storageBucket: 'abayedir.firebasestorage.app',
    iosBundleId: 'com.example.abayEqub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK5jVAeIdXaCY6lXeEe9l9cZLXITVsIGQ',
    appId: '1:895055745889:web:7900172a725f9a7757eb20',
    messagingSenderId: '895055745889',
    projectId: 'abayedir',
    authDomain: 'abayedir.firebaseapp.com',
    storageBucket: 'abayedir.firebasestorage.app',
    measurementId: 'G-8NMF0GY79K',
  );
}
